config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :audios, except: :destroy

  root "audios#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/audio.rb
class Audio < ApplicationRecord
  after_commit :create_streamable_media, if: :audio_url_previously_changed?

  def create_streamable_media(now: false)
    if now
      CreateStreamableMediaJob.perform_now(self, :audio_url, :audio_stream_url)
    else
      CreateStreamableMediaJob.perform_later(self, :audio_url, :audio_stream_url)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/audios_controller.rb
class AudiosController < ApplicationController
  # Actions
  #########

  def index
    @record = Audio.last
    redirect_to action: :new if @record.blank?
  end
  
  def new
    @record = Audio.new
  end

  def create
    redirect_to action: :new if permitted_params[:audio_url].blank?
    
    @record = Audio.new
    file = client.store(permitted_params[:audio_url])
    @record.audio_url = file.url
    if @record.save
      redirect_to action: :index, notice: 'Audio was successfully created. Please wait a few minutes for the audio to be processed.'
    else
      render action: 'new'
    end
  rescue Filepicker::ClientError => e
    redirect_to action: :new, alert: e.message
  end

  def edit
    @record = Audio.find(params[:id])
  end

  def update
    redirect_to action: :edit if permitted_params[:audio_url].blank?

    @record = Audio.find(params[:id])
    file = client.store(permitted_params[:audio_url])
    if @record.update(audio_url: file.url)
      redirect_to action: :index, notice: 'Audio was successfully updated.'
    else
      render action: 'edit'
    end
  rescue Filepicker::ClientError => e
    redirect_to action: :edit, alert: e.message
  end

  private

  def permitted_params
    params.permit(:audio_url)
  end

  def client
    @client ||= Filepicker::Client.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/audios/_audio_player.html.erb
<% return if @record.blank? %>

<%= tag.div(
  data: {
    controller: "audio-player",
    audio_player_stream_url: @record.audio_stream_url,
    audio_player_fallback_url: @record.audio_url
  }
) do %>
  <% if @record.audio_stream_url.present? %>
    <%= tag.p "Audio has been successfully converted for streaming." %>
  <% elsif @record.audio_url.present? %>
    <%= tag.p "We are still waiting for this audio to be converted for streaming." %>
  <% else %>
    <%= tag.p "This audio record doesn't have any audio uploaded." %>
  <% end %>

  <%= tag.video(
    controls: true,
    playsinline: true,
    preload: "metadata",
    data: { audio_player_target: "video" }
  ) %>
  <%= tag.audio(
    style: "display: none;",
    controls: true,
    playsinline: true,
    preload: "metadata",
    data: { audio_player_target: "audio" }
  ) %>
<% end %>

app/views/audios/_edit_form.html.erb
<%= form_for(@record, multipart: true) do %>
  <% if @record.audio_url.present? %>
    <%= tag.p style: "margin-bottom: 1em" do %>
      Current audio URL: <%= link_to(@record.audio_url, @record.audio_url) %>
    <% end %>
    <%= tag.p style: "margin-bottom: 2em" do %>
      <% if @record.audio_stream_url.present? %>
        Audio stream URL: <%= link_to(@record.audio_stream_url, @record.audio_stream_url) %>
      <% else%>
        Audio stream URL: <%= link_to("Not yet available", StreamableMedia.conversion_endpoint(@record.audio_url)) %>
      <% end %>
    <% end %>
  <% end %>

  <%= tag.div style: "margin-bottom: 2em" do %>
    <%= label_tag :audio_url do %>
      <%= tag.p "Upload a new audio file:" %>
      <%= file_field_tag "audio_url" %>
    <% end %>
    <%= tag.p "Only upload MP3s please" %>
  <% end %>

  <%= button_tag(
    "Submit",
    type: :submit
  ) %>
<% end %>

app/views/audios/edit.html.erb
<%= tag.h1 "Upload audio" %>
<%= render partial: "edit_form" %>

app/views/audios/index.html.erb
<%= tag.h1 "Stream audio" %>

<%= tag.div style: "margin-bottom: 2em" do %>
  <%= render partial: "audio_player" %>
<% end %>

<%= tag.p(
  link_to "Edit the audio", edit_audio_path(@record)
) %>

app/views/audios/new.html.erb
<%= tag.h1 "Upload audio" %>
<%= render partial: "edit_form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StreamingMediaReproduction</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>